### ISSUE TITLE
[BUG] redundant request

### ISSUE THREAD

**Issue by joankosev** [iossifovlab/gpfjs#1061]
phenotype tool measures request is made once when the tool loads, and then a second time when the user clicks on advanced family/person filters
dataset description - study request for description is made twice
agp single view

**Comment by IvoStefanov** [comment]
1. Phenotype tool measures request is done twice because two different components use it. One is loaded with the tool the other when advanced family/person filters is clicked.

2. "dataset description - study request for description is made twice"
False or can't reproduce.

3. "agp single view"
Please give more details.
